#!/bin/zsh

for NUM in $(seq 0 7); do
      printf "\e[0;3${NUM}m███████ "
done

printf "\n"
for NUM in $(seq 0 7); do
      CN=$(xrdb -query | grep "^\*color${NUM}:"| cut -d':' -f2 | tr -d '\t')
      printf "\e[0;3${NUM}m%s " $CN
done
echo
for NUM in $(seq 0 7); do
    CN=$(xrdb -query | grep "^\*color$((${NUM} + 8)):"| cut -d':' -f2 | tr -d '\t')
      printf "\e[1;3${NUM}m%s " $CN
done
echo
for NUM in $(seq 0 7); do
      printf "\e[1;3${NUM}m███████ "
done
printf "\e[0m\n"
