#!/bin/sh
# perform a search on youtube and return the best result (title + link)

usage() {
    echo "`basename $0` [-htu] [-n <num>] <query>"

    test -z "$1" && return

    cat <<EOF
        -h : display this help
        -t : output titles only (default 'title - uri')
        -u : output uris only
        -n : print only <num> results (default: 3)
EOF
}

num_results=3
regex='^.*<a href="\(/watch[^"]*\)"[^>]*>\([^<]*\)</a>.*$'
output='\2 \| https://youtube.com\1'

while getopts "hn:tu" OPT; do
    case  $OPT in
        h) usage long; exit 0;;
        n) num_results=$OPTARG;;
        t) output='\2';;
        u) output='https://youtube.com\1';;
        *) usage; exit 1;;
    esac
done

shift $((OPTIND - 1))

query=$(echo $@ | tr ' ' '+')
url="https://www.youtube.com/results?search_query=${query}"
curl -s "$url" | sed -n "s,$regex,$output,p" | sed ${num_results}q
